---
#-------------------------------
# General Site Settings

title: Turkish NLP Suite
logo:  /assets/images/logo/tnlplogo.png 
author: themefisher
description: this is meta description
email: duygu dot altinok12 at gmail.com
github: https://github.com/turkish-nlp-suite
linkedin: https://www.linkedin.com/in/duygu-altinok-4021389a/
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Resources, link: "/resources" }
  - { name: Publications, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# About (Section and Page)


# About Section

blurb: Turkish NLP Suite is a nonprofit organization that aims to deliver resources for Turkish NLP, including corpus, pretrained models, benchmarking resources and much more. We aim to bring excellence to the Turlish language and speech research by publishing and open-sourcig for all areas of Turkish processing including morphology, language modelling, subword modelling, corpora building and more. The organization is run by Duygu, your research scientist (originally )from Istanbul, (currently) living in Berlin and San Diego, CA. 


blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Large-scale Turkish Corpus, color: "#fdb157", value: "99%" }
  - { name: Pretrained Turkish Models, color: "#9473e6", value: "99%" }
  - { name: Publications, color: "#bdecf6", value: "99%" }
  - { name: Educational Material, color: "#ffbcaa", value: "99%" }


#-------------------------------
# Publications (Section and Page)

# Publications Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Publications Page
portfolio-label:
  - { title: "Model", type: "design" }
  - { title: "Dataset", type: "design" }
  - { title: "Corpus", type: "branding" }
  - { title: "Research", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-9.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-10.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-11.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------

contact-title: Contact Info
contact-email: duygu.altinok12@gmail.com
