---
#-------------------------------
# General Site Settings

title: Turkish NLP Suite
logo:  
author: themefisher
description: this is meta description
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Resources, link: "/resources" }
  - { name: Publications, link: "/portfolio" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# About (Section and Page)


# About Section

blurb: Turkish NLP Suite is a nonprofit organization that aims to deliver resources for Turkish NLP, including corpus, pretrained models, benchmarking resources and much more. We aim to bring excellence to the Turlish language and speech research by publishing and open-sourcig for all areas of Turkish processing including morphology, language modelling, subword modelling, corpora building and more. The organization is run by Duygu, your research scientist (originally )from Istanbul, (currently) living in Berlin and San Diego, CA. 


blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Large-scale Turkish Corpus, color: "#fdb157", value: "99%" }
  - { name: Pretrained Turkish Models, color: "#9473e6", value: "99%" }
  - { name: Publications, color: "#bdecf6", value: "99%" }
  - { name: Tutorials, color: "#ffbcaa", value: "99%" }


#-------------------------------
# Publications (Section and Page)

# Publications Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/morph.png"
    url: "https://link.springer.com/chapter/10.1007/978-3-031-09909-0_12"

  - image: "assets/images/portfolio/diverse.png"
    url: "https://aclanthology.org/2023.acl-long.768/"

  - image: "assets/images/portfolio/gender.png"
    url: "https://aclanthology.org/2024.gebnlp-1.13.pdf"

  - image: "assets/images/portfolio/bella.png"
    url: "https://link.springer.com/chapter/10.1007/978-3-031-70563-2_16"

  - image: "assets/images/portfolio/item-5.png"
    url: "https://medium.com/p/2b33e694dd78"

  - image: "assets/images/portfolio/item-6.png"
    url: "https://medium.com/p/ce65ece62aea"

  - image: "assets/images/portfolio/item-7.png"
    url: "https://medium.com/p/ce65ece62aea"

  - image: "assets/images/portfolio/item-8.png"
    url: "https://medium.com/p/fc83ca3c95df"

  - image: "assets/images/portfolio/item-9.png"
    url: "https://medium.com/google-developer-experts/brand-new-spacy-turkish-models-304da649eacc"

  - image: "assets/images/portfolio/item-10.png"
    url: "https://medium.com/google-developer-experts/quick-recipes-with-spacy-turkish-how-is-your-infection-doing-4ee1421b2443"

  - image: "assets/images/portfolio/item-11.png"
    url: "https://medium.com/google-developer-experts/instructurca-an-open-source-instruction-tuning-dataset-for-turkish-18c37b0e99b9"

# Publications Page
portfolio-label:
  - { title: "Model", type: "model" }
  - { title: "Dataset", type: "dataset" }
  - { title: "Corpus", type: "corpus" }
  - { title: "Research", type: "research" }
  - { title: "Medium Blog Post", type: "medium" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    description: "A Statistical Approach to Analyzing Turkish Morphology"
    url: "https://link.springer.com/chapter/10.1007/978-3-031-09909-0_12"
    portfolio-type:
      - type: "research"

  - image: "assets/images/portfolio/item-2.png"
    url: "https://aclanthology.org/2023.acl-long.768/"
    description: "A Diverse Set of Freely Available Linguistic Resources for Turkish"
    portfolio-type:
      - type: "dataset"
      - type: "model"

  - image: "assets/images/portfolio/item-3.png"
    url: "https://aclanthology.org/2024.gebnlp-1.13.pdf"
    description: "Gender Bias in Turkish Word Embeddings: A Comprehensive Study of Syntax, Semantics and Morphology Across Domains"
    portfolio-type:
      - type: "research"

  - image: "assets/images/portfolio/item-4.png"
    description: "BellaTurca:A Large-Scale Dataset of Diverse Text Sources for Turkish Language Modeling"
    url: "https://link.springer.com/chapter/10.1007/978-3-031-70563-2_16"
    portfolio-type:
      - type: "corpus"

  - image: "assets/images/portfolio/item-5.png"
    description: "Turkish NLP, A Gentle Introduction"
    url: "https://medium.com/p/2b33e694dd78"
    portfolio-type:
      - type: "medium"

  - image: "assets/images/portfolio/item-6.png"
    url: "https://medium.com/p/ce65ece62aea"
    description: "Turkish Phonetics, A Quick Intro"
    portfolio-type:
      - type: "medium"

  - image: "assets/images/portfolio/item-7.png"
    url: "https://medium.com/p/ce65ece62aea"
    description: "Neden yasaklandı? Depremle ilgili Ekşi Sözlük yorumlarına NLP gözüyle bakış"
    portfolio-type:
      - type: "medium"

  - image: "assets/images/portfolio/item-8.png"
    url: "https://medium.com/p/fc83ca3c95df"
    description: "A collection of new datasets for Turkish NLP"
    portfolio-type:
      - type: "medium"

  - image: "assets/images/portfolio/item-9.png"
    url: "https://medium.com/google-developer-experts/brand-new-spacy-turkish-models-304da649eacc"
    description: "Brand new spaCy Turkish models"
    portfolio-type:
      - type: "medium"

  - image: "assets/images/portfolio/item-10.png"
    url: "https://medium.com/google-developer-experts/quick-recipes-with-spacy-turkish-how-is-your-infection-doing-4ee1421b2443"
    description: "Quick recipes with spaCy Turkish: How is your infection doing"
    portfolio-type:
      - type: "medium"

  - image: "assets/images/portfolio/item-11.png"
    url: "https://medium.com/google-developer-experts/instructurca-an-open-source-instruction-tuning-dataset-for-turkish-18c37b0e99b9"
    description: "InstrucTurca:An open source instruction tuning dataset for Turkish"
    portfolio-type:
      - type: "medium"



#-------------------------------
# Resources (Section and Page)

# Resources Home Section
resources-home-items:
  - image: "assets/images/resources/havadis.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/Havadis"

  - image: "assets/images/resources/bella.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/BellaTurca"

  - image: "assets/images/resources/ozenli.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/OzenliDerlem"

  - image: "assets/images/resources/akademik.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/AkademikDerlem"

  - image: "assets/images/resources/temiz-oscar.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/temiz-OSCAR"

  - image: "assets/images/resources/temiz-mc4.png"
    url: "huggingface.co/datasets/turkish-nlp-suite/temiz-mC4"

  - image: "assets/images/resources/sentiturca.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/SentiTurca"

  - image: "assets/images/resources/tuhama.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/TurkishHateMap"

  - image: "assets/images/resources/musteri.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/MusteriYorumlari"

  - image: "assets/images/resources/instructurca.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/InstrucTurca"

  - image: "assets/images/resources/trspacy.png"
    url: "https://huggingface.co/collections/turkish-nlp-suite/turkish-spacy-models"


# Resources Page
resource-label:
  - { title: "Model", type: "model" }
  - { title: "Corpus", type: "corpus" }
  - { title: "Dataset", type: "dataset" }

resource-items:
  - image: "assets/images/resources/havadis.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/Havadis"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/bella.png"
    url: "https://huggingface.co/datasets/BayanDuygu/BellaTurca"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/ozenli.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/OzenliDerlem"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/akademik.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/AkademikDerlem"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/temiz-oscar.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/temiz-OSCAR"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/temiz-mc4.png"
    url: "huggingface.co/datasets/turkish-nlp-suite/temiz-mC4"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/sentiturca.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/SentiTurca"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/tuhama.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/TurkishHateMap"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/musteri.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/MusteriYorumlari"
    resource-type:
      - type: "corpus"
  - image: "assets/images/resources/instructurca.png"
    url: "https://huggingface.co/datasets/turkish-nlp-suite/InstrucTurca"
    resource-type:
      - type: "dataset"
  - image: "assets/images/resources/trspacy.png"
    url: "https://huggingface.co/collections/turkish-nlp-suite/turkish-spacy-models"
    resource-type:
      - type: "model"
